# .streamlit/secrets.toml

# Spreadsheet ID is the long part of:
# https://docs.google.com/spreadsheets/d/<SPREADSHEET_ID>/edit#gid=0
spreadsheet_id = "11E61euIdogiqBwm1NgzRO-5VQbHkRpBz07ha6UvQls4"

# Path to your service account json file (relative to repo root)
service_account_json_path = "secrets/gpc_service_account.json"

# Worksheet/tab name inside the spreadsheet
inventory_worksheet = "inventory"

refresh_token = "PASTE_YOUR_REFRESH_TOKEN_HERE"
